services:
  db:
    container_name: "postgresql"
    image: postgres:alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=appdb
      - POSGRES_USER=appuser
      - POSTGRES_PASSWORD=passw